baseURL = "https://blog.alt-engineering.com/"
languageCode = 'en-us'
title = 'alternative engineering'
theme = "m10c"

[params]
author = "Martin Zielinski"
description = "Private blog about engineering and other ramblings"

    [params.contact]
    author = "Martin Zielinski"
    email = "info@example.org"

    [[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/darthcoder1"

    [[params.social]]
    icon = "mastodon"
    name = "Mastodon"
    url = "https://mastodon.gamedev.place/@darthcoder1"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4