baseURL = "https://blog.alt-engineering.com/"
languageCode = 'en-us'
title = 'alternative engineering'
theme = "m10c"

[params]
author = "Martin Zielinski"
description = "Personal blog about software engineering, game development, the tech industry and other random stuff I care about."

[params.contact]
author = "Martin Zielinski"
email = "mailto:info@example.org"

[[params.social]]
icon = "mail"
name = "e-mail"
url = "mailto:martin@alt-engineering.com"

[[params.social]]
icon = "at-sign"
name = "Mastodon"
url = "https://mastodon.gamedev.place/@darthcoder1"

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://x.com/DarthCoder"

[[params.social]]
icon = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/martin-zielinski/"

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/darthcoder1"

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#afbac4"
  lightestColor = "#ffffff"
  primaryColor = "#57cc8a"

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#afbac4"
  lightestColor = "#ffffff"
  primaryColor = "#57cc8a"