on: [push]
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.131.0
      BASE_URL: blog.alt-engineering.com
    steps:
      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Berlin
        run: |
          # build
          hugo \
            --config hugo.toml \
            --gc \
            --minify \
            --baseURL "${BASE_URL}"
          # compress artifact
          tar cfz public-www.tar.gz ./public
      - uses: actions/upload-artifact@v3
        with:
          name: public-www.tar.gz
          path: ./public-www.tar.gz
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      BASE_URL: blog.alt-engineering.com
    steps:
      - name: Install rsync
        run: |
          apt-get update
          apt-get install -y rsync
      - uses: actions/download-artifact@v3
        with:
          name: public-www.tar.gz
          path: ./
      - name: Uncompress
        run: |
          ls -la
          tar xzvf ./public-www.tar.gz
      - name: Deploy to VPS via rsync
        env:
          RSYNC_TARGET: /opt/www/${{env.BASE_URL}}/
          RSYNC_SOURCE: ./public
        run: |
          ls -la ~/.ssh
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 400  ~/.ssh/id_rsa

          ssh -i  ~/.ssh/id_rsa ${{secrets.SSH_USER_NAME}}@${{secrets.SSH_HOST_NAME}} ls -la

          rsync -avzr --delete -e "ssh -i  ~/.ssh/id_rsa" $RSYNC_SOURCE ${{secrets.SSH_USER_NAME}}@${{secrets.SSH_HOST_NAME}}:$RSYNC_TARGET
          rm  ~/.ssh/id_rsa
